dataset:
  batch_size: 4
  calib_dir: ./data/pse_dataset.txt
  calib_num: 100
  preprocessing:
    attributes:
      isreverses: true
      mean:
      - 123.675
      - 116.28
      - 103.53
      resize:
        keep_ratio: false
        to:
        - 3
        - 736
        - 1280
      std:
      - 58.395
      - 57.120000000000005
      - 57.375
    enable: true
    type: preprocess_v1
export_model: pd_dbnet_736x1280/det_mv3_db_int8_maca.onnx
export_type: maca
import_model: pd_dbnet_736x1280/det_mv3_db.onnx
force_advance_quant: true

optimize:
  decompose_bias: 
    ops: ["p2o.Conv.13"]
  training:
    lr: 3e-5
    steps: 1500